### ISSUE TITLE
Cannot use .evaluate or .$eval

### ISSUE THREAD

**Issue by GirkovArpa** [TrevorSundberg/puppeteer-in-electron#16]
Anytime I use `page.evaluate()` or `page.$eval()` I get this error, although other functions work normally:

```
Error: Evaluation failed: ReferenceError: sender is not defined
    at __puppeteer_evaluation_script__:3:11
```

**Comment by GirkovArpa** [comment]
It works when executed in the context of the main process, but not the renderer process.  

Why?

This is such an inconvenient workaround, having to evaluate an evaluate:

> renderer.js
```javascript
const { ipcRenderer } = electron;
ipcRenderer.sendSync('foo', `page.$eval('console.log("Hello World!")')`);
```

> main.js
```javascript
const { ipcMain } = electron;
ipcMain.on('foo', (event, arg) => event.returnValue = eval(arg));
```

**Comment by TrevorSundberg** [comment]
Do you have a minimum repro? I just added `await page.evaluate(() => console.log("hello world"));` to the `test.ts` file after `console.log(page.url());` and it is working as expected.

**Comment by GirkovArpa** [comment]
Sure thing:
> main.js
```javascript
(async () => {
  const { BrowserWindow, app } = require('electron');
  const pie = require('puppeteer-in-electron')
  const puppeteer = require('puppeteer-core');
  const path = require('path');
  await pie.initialize(app);
  const browser = await pie.connect(app, puppeteer);
  const window = new BrowserWindow({ webPreferences: { nodeIntegration: true } });
  window.webContents.openDevTools();
  await window.loadURL(path.join(__dirname, 'index.html'));
  global.page = await pie.getPage(browser, window);
  window.webContents.send('foo');
})();
```
> index.html
```html
<button onclick="alert('Hello World!')">Click me!</button>
<script>
  const { remote, ipcRenderer } = require('electron');
  ipcRenderer.on('foo', async () => await (remote.getGlobal('page')).$eval('button', btn => btn.click()));
</script>
```
```
Uncaught (in promise) Error: Evaluation failed: ReferenceError: sender is not defined
    at __puppeteer_evaluation_script__:3:21
    at ExecutionContext._evaluateInternal 
```

**Comment by TrevorSundberg** [comment]
Thanks for that min repro! I'm not certain what is happening, however I did find this in puppeteer:

https://github.com/puppeteer/puppeteer/issues/3731

Are you using webpack or another transpiler? If so, I think this is the issue:

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#code-transpilation-issues

**Comment by GirkovArpa** [comment]
That first link is actually the only place on the internet describing this same issue, but I'm not using any transpiler.

**Comment by TrevorSundberg** [comment]
When I run your test with `electron ./main.js` I get `UnhandledPromiseRejectionWarning: Error: ERR_INVALID_URL (-300) loading ''`, I believe because `window.loadURL` doesn't accept file paths. How does your min repro work? I can try and add `file://` to the front but then I just get security errors with `Insecure Content-Security-Policy`.

**Comment by GirkovArpa** [comment]
I'm running it with `npm start`, here is my `package.json`:
> package.json
```javascript
{
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "dependencies": {
    "electron": "^9.0.4",
    "puppeteer-core": "^4.0.0",
    "puppeteer-in-electron": "^3.0.2"
  }
}
```

**Comment by GirkovArpa** [comment]
Why is the close button on the left?

**Comment by TrevorSundberg** [comment]
I still can't run your sample, I have `main.js`, `index.html`, and `package.json`. I ran `npm install` and then `npm start`. Same error:

```bash
trevor@tvok:~/pietest$ npm start

> @ start /home/trevor/pietest
> electron .


DevTools listening on ws://127.0.0.1:46687/devtools/browser/f5a0ca26-b534-4cbf-94cb-f37a33e84eb0
(node:30995) UnhandledPromiseRejectionWarning: Error: ERR_INVALID_URL (-300) loading ''
    at rejectAndCleanup (electron/js2c/browser_init.js:6327:21)
    at WebContents.failListener (electron/js2c/browser_init.js:6337:11)
    at WebContents.emit (events.js:223:5)
    at WebContents../lib/browser/navigation-controller.js.NavigationController.loadURL (electron/js2c/browser_init.js:6384:22)
    at BrowserWindow.loadURL (electron/js2c/browser_init.js:650:29)
    at /home/trevor/pietest/main.js:10:18
(node:30995) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30995) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by GirkovArpa** [comment]
I'm on Windows 10.

**Comment by TrevorSundberg** [comment]
Closing this because I'm not able to repro this behavior.
