### ISSUE TITLE
Package no longer works with latest electron ( 21.1.1 )

### ISSUE THREAD

**Issue by Naozumi520** [TrevorSundberg/puppeteer-in-electron#54]
`After updated to electron 21.1.1`:

```
(node:2316) UnhandledPromiseRejectionWarning: Error: The parameter 'browser' was not passed in.
    at Object.getPage (C:\Users\zumi\Desktop\electron-puppeteer\node_modules\puppeteer-in-electron\bin\index.js:92:15)
    at environment (C:\Users\zumi\Desktop\electron-puppeteer\main.js:732:20)
(Use `electron --trace-warnings ...` to show where the warning was created)
22:27:30.200 > UnhandledPromiseRejectionWarning: Error: The parameter 'browser' was not passed in.
    at Object.getPage (C:\Users\zumi\Desktop\electron-puppeteer\node_modules\puppeteer-in-electron\bin\index.js:92:15)
    at environment (C:\Users\zumi\Desktop\electron-puppeteer\main.js:732:20)
    at emitUnhandledRejectionWarning (node:internal/process/promises:191:15)
    at processPromiseRejections (node:internal/process/promises:270:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:97:32)
(node:2316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
22:27:30.202 > Error: The parameter 'browser' was not passed in.
    at Object.getPage (C:\Users\zumi\Desktop\electron-puppeteer\node_modules\puppeteer-in-electron\bin\index.js:92:15)
    at environment (C:\Users\zumi\Desktop\electron-puppeteer\main.js:732:20)
```

**Comment by Naozumi520** [comment]
It looks like Berg is no longer active on github, anyone who find an alternator please let me know, I would appreciate for any help. 
It's definitely not a permanent way to keep programs working with older versions of electron.

**Comment by zoom2009** [comment]
May be another problem, This package still work fine. I just create new project last hour.

here my version
```javascript
"electron": "^21.2.2",
"puppeteer-core": "^19.2.2",
"puppeteer-in-electron": "^3.0.5",
```

here my test code
```javascript
const path = require('path')
const {app, BrowserWindow} = require('electron')
const pie = require("puppeteer-in-electron")
const puppeteer = require("puppeteer-core")

const createWindow = async () => {
  try {
    const browser = await pie.connect(app, puppeteer);
  
    const window = new BrowserWindow();
    const url = "https://google.co.th/";
    await window.loadURL(url);
  
    const page = await pie.getPage(browser, window);
    console.log(page.url());
  } catch (e) {
    console.log('some error e:', e)
  }
}

pie.initialize(app)
app.on('will-finish-launching', () => {
  createWindow()
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})
```

**result**

<img width="753" alt="image" src="https://user-images.githubusercontent.com/33366155/200240739-02674453-e15a-4629-9da1-74904e50f2fc.png">
